name: Covid19PushFetch

on: 
  schedule:
    - cron: "30 0 * * SUN-SAT"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run etl on csv files
      run: python eda.py
    - name: Commit files
      run: |
        git config --global user.name 'TJMusiitwa'
        git config --global user.email 'jonamusiitwa@outlook.com'
        git commit -am "Updated csv files"
        git push    
